MOVE_GUARANTEED_KO_BONUS = 100.0
MOVE_POSSIBLE_KO_BONUS = 50.0
MOVE_PRIORITY_BONUS = 5.0

SWITCH_RESISTS_BEST_MOVE_BONUS = 30.0
SWITCH_THREATENS_KO_BONUS = 20.0
SWITCH_HAS_RECOVERY_BONUS = 10.0
SWITCH_OVER_HALF_DAMAGE_PENALTY = 40.0
SWITCH_KO_RANGE_PENALTY = 50.0

RELIABLE_RECOVERY_MOVES = {"recover", "roost", "slackoff", "softboiled"}

